export const DELETE_ITEM: 'DELETE_ITEM' = 'DELETE_ITEM'
export const ADD_ITEM: 'ADD_ITEM' = 'ADD_ITEM'
export const CHANGE_ITEM: 'CHANGE_ITEM' = 'CHANGE_ITEM'

export const GET_ITEMS_REQUEST: 'GET_ITEMS_REQUEST' = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS' = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILED: 'GET_ITEMS_FAILED' = 'GET_ITEMS_FAILED';

export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED:'GET_ORDER_FAILED' = 'GET_ORDER_FAILED';